### PR TITLE
Fix tracing bug

### LINKED ISSUE #51: Multiple transactions in single block errors with `MerkleWitness not valid for StateTransition`
**Describe the bug**
When sending many transactions to an app-chain & then producing a block the test errors with:
```bash
test/Balances.test.ts:
Block Production time: 1696 milliseconds
111 |         if (response.taskId !== undefined) {
112 |             const resolveFunction = this.resultsPending[response.taskId];
113 |             if (!this.erroredOut) {
114 |                 if (response.status === "error") {
115 |                     this.erroredOut = true;
116 |                     this.errorFunction?.(new Error(`Error in worker: ${response.payload}`));
                                            ^
error: Error in worker: MerkleWitness not valid for StateTransition (0, type normal)
Bool.assertTrue(): false != true
```

I came across this error in both `bun` and `npm`.

**To Reproduce**
1. Go to [bun bug repository](https://github.com/teddyjfpender/proto-kit-bun-project) or the [npm bug repository](https://github.com/teddyjfpender/proto-kit-npm-project)
2. Run the tests (`bun install && bun test` or `npm test`)
3. See error

**Expected behavior**
When sending multiple transactions to the app-chain it should produce a block and not error.

**Additional context**

### PR DESCRIPTION
**Pull request by rpanic**
Fix bug where previously written merkle-tree entries got overwritten by preloading

closes #51

### CODE REVIEW

File: packages/protocol/src/prover/statetransition/StateTransitionProver.ts [hunk 1]
```diff
@@ -203,6 +203,12 @@ export class StateTransitionProverProgrammable extends ZkProgrammable<
       transition.from.value
     );
 
+    // if (!membershipValid.toBoolean()) {
```
Comment (maht0rz) [inline packages/protocol/src/prover/statetransition/StateTransitionProver.ts]: seems like an artifact from debuging, should we remove this?

File: packages/sequencer/src/protocol/production/TransactionTraceService.ts [hunk 2]
```diff
@@ -397,35 +485,44 @@ export class TransactionTraceService {
...
+  ): Promise<{
     runtimeKeys: Field[];
     protocolKeys: Field[];
-  } {
+  }> {
     // Execute the first time with dummy service
-    this.runtime.stateServiceProvider.setCurrentStateService(
-      this.dummyStateService
-    );
+    // this.runtime.stateServiceProvider.setCurrentStateService(
```
Comment (maht0rz) [inline packages/sequencer/src/protocol/production/TransactionTraceService.ts]: probably a debug artifact, should we remove?

File: packages/sequencer/src/protocol/production/execution/CachedStateService.ts [hunk 3]
```diff
@@ -32,13 +35,15 @@ export class CachedStateService
...
     if (this.parent !== undefined && this.get(key) === undefined) {
       const value = await this.parent.getAsync(key);
-      log.debug(
-        `Preloading ${key.toString()}: ${
-          // eslint-disable-next-line max-len
-          // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
-          value?.map((element) => element.toString()) ?? []
-        }`
-      );
+      if (this.debugLogs) {
```
Comment (maht0rz) [inline packages/sequencer/src/protocol/production/execution/CachedStateService.ts]: do we need this extra layer of logging enable/disable? wouldnt setLevel('DEBUG') be enought?

Comment (rpanic) [reply packages/sequencer/src/protocol/production/execution/CachedStateService.ts]: I think so, yes. This i mainly for debugging issues on our side, so nothing that should be logged for the user. And since there is no log level belug DEBUG, i opted for this approach

**Review by maht0rz — APPROVED** [review]
